# Generated by Django 2.1.2 on 2019-05-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
